# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
	  v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "serveripa" do |serveripa|
    serveripa.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "dns"
    serveripa.vm.network "private_network", ip: "192.168.56.10"
    serveripa.vm.hostname = "serveripa"
  end

  config.vm.define "clientipa" do |clientipa|
    clientipa.vm.network "private_network", ip: "192.168.50.20", virtualbox__intnet: "dns" 
    clientipa.vm.network "private_network", ip: "192.168.56.20"
    clientipa.vm.hostname = "clientipa"

    clientipa.vm.provision "ansible" do |ansible|
      #ansible.verbose = "vvv"
      ansible.playbook = "playbook.yml"
      ansible.become = "true"
      ansible.host_key_checking = "false"
      ansible.limit = "all"
    end  
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd
    setenforce 0
    sed -i "s/SELINUX=enforcing/SELINUX=disabled/" /etc/selinux/config
  SHELL
  
end
